### ISSUE TITLE
(undeterministic) test failures in rng test

### ISSUE THREAD

**Issue by carnil** [RafaelOstertag/yapet#13]
Hi Rafael,

While uploading yapet 2.0 version for Debian, the package failed to build on two architectures ([amd64](https://buildd.debian.org/status/fetch.php?pkg=yapet&arch=amd64&ver=2.0-1&stamp=1540336057&raw=0) and [arm64](https://buildd.debian.org/status/fetch.php?pkg=yapet&arch=arm64&ver=2.0-1&stamp=1540335903&raw=0)).

The architecture itself is probably not relevant, because the package builded before uploading into the archive as well on amd64.

Any ideas on a possible cause?

**Comment by RafaelOstertag** [comment]
Hi

The issue can easily be reproduced by running the test multiple times
```shell
while ./rng ; do : ; done
```
The problem is caused by the move assignment operator not properly cleaning up the source object.
I'm rolling release 2.1 which addresses the issue.

**Comment by carnil** [comment]
Hi Rafael,

On Sat, Oct 27, 2018 at 06:12:19AM -0700, Rafael Ostertag wrote:
> Hi
> 
> The issue can easily be reproduced by running the test multiple times
> ```shell
> while ./rng ; do : ; done
> ```
> The problem is caused by the move assignment operator not properly cleaning up the source object.
> I'm rolling release 2.1 which addresses the issue.

Should fill maybe a new issue, but as heads up: I still get
(undeterminstically) build failures either on our CI infrastructure
(cf. https://salsa.debian.org/carnil/yapet/-/jobs which might suceed
after retrying) or on our build infrastructure:
https://buildd.debian.org/status/package.php?p=yapet .

**Comment by RafaelOstertag** [comment]
Yes, I saw them. But so far I'm not able to come up with a method to reproduce them. I'll keep an eye on it, though.

**Comment by carnil** [comment]
Hi,

On Wed, Oct 31, 2018 at 12:50:20AM -0700, Rafael Ostertag wrote:
> Yes, I saw them. But so far I'm not able to come up with a method to
> reproduce them. I'll keep an eye on it, though.

Alright.

Do you prefer to have a new issue opened for those individually as I
notice or will you want to keep it track differently?

Btw, many thanks for your upstream work!

**Comment by RafaelOstertag** [comment]
Hey,

You're welcome!

I'd prefer if you open a new issue upon notice.
