### ISSUE TITLE
Pressing 'i' gives "basic_string::_S_construct null not valid"

### ISSUE THREAD

**Issue by gebailey** [RafaelOstertag/yapet#17]
I'm the packager for `yapet` on Fedora, RHEL, and CentOS distributions, and am testing out modifications to the RPM spec file to support yapet-2.2.  On my CentOS 7 workstation, I've built yapet-2.2 using devtoolset-7 (GCC 7.3.1) and yapet-2.2 appears to read my existing password file OK.  If I press the "I" key (for information), the program exits with "basic_string::_S_construct null not valid".

I've tried to create a yapet-1.1 test password file, and I can load that one with yapet-2.2 and press "I" without a crash.

I've created a new yapet-2.2 test password file, and I can press "I" without a crash.

There seems to be something with my existing password file that causes "I" to crash on yapet-2.2 but not sure how to troubleshoot this.  (I'm not a C++ programmer).  Any suggestions for debugging this?

**Comment by RafaelOstertag** [comment]
Thank you for bringing this to my attention. I was able to reproduce the null pointer you described. It can be triggered by loading the files `f64le0.6.pet.in` or `f32be0.6.pet.in` in the `tests/crypt` directory.

I'm going to roll a new release in the next couple of days.

**Comment by RafaelOstertag** [comment]
I just released version 2.3 which fixes this issue.
