### ISSUE TITLE
Make failed on gentoo 

### ISSUE THREAD

**Issue by lovelytux** [RafaelOstertag/yapet#19]
Hello!
Please I need help. I use gentoo. It is not possible to run the make-script. 
./configure gives:
...
...
******************************************************************

Prefix              : /usr/local
CPPFLAGS            : 
CFLAGS              : -g -O2
CXXFLAGS            : -g -O2
LDFLAGS             : 

Enable debug code   : no
Disable install Doc.: no

Use NLS             : yes

******************************************************************

Looks good.

And make:
make  all-recursive
make[1]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3'
Making all in libyacurs
make[2]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs'
make  all-recursive
make[3]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs'
Making all in po
make[4]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/po'
make[4]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/po'
Making all in include
make[4]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/include'
make  all-am
make[5]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/include'
make[5]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/include'
make[4]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/include'
Making all in src
make[4]: Entering directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/src'
  CXX      libyacurs_la-curstr.lo
In file included from ../include/colors.h:29,
                 from ../include/curstr.h:28,
                 from curstr.cc:22:
../include/yacurscurses.h:44:2: error: #error "SysV or X/Open-compatible Curses header file required"
 #error "SysV or X/Open-compatible Curses header file required"
  ^~~~~
In file included from ../include/colors.h:29,
                 from ../include/curstr.h:28,
                 from curstr.cc:22:
../include/yacurscurses.h:117:22: warning: inline variables are only available with -std=c++17 or -std=gnu++17
 inline int waddstr_c(WINDOW* win, const char* str) {
                      ^~~~~~
../include/yacurscurses.h:117:22: error: ‘WINDOW’ was not declared in this scope
../include/yacurscurses.h:117:30: error: ‘win’ was not declared in this scope
 inline int waddstr_c(WINDOW* win, const char* str) {
                              ^~~
../include/yacurscurses.h:117:35: error: expected primary-expression before ‘const’
 inline int waddstr_c(WINDOW* win, const char* str) {
                                   ^~~~~
../include/yacurscurses.h:117:50: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int waddstr_c(WINDOW* win, const char* str) {
                                                  ^
In file included from ../include/colors.h:29,
                 from ../include/curstr.h:28,
                 from curstr.cc:22:
../include/yacurscurses.h:140:24: warning: inline variables are only available with -std=c++17 or -std=gnu++17
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                        ^~~~~~
../include/yacurscurses.h:140:24: error: ‘WINDOW’ was not declared in this scope
../include/yacurscurses.h:140:32: error: ‘win’ was not declared in this scope
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                                ^~~
../include/yacurscurses.h:140:37: error: expected primary-expression before ‘int’
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                                     ^~~
../include/yacurscurses.h:140:44: error: expected primary-expression before ‘int’
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                                            ^~~
../include/yacurscurses.h:140:51: error: expected primary-expression before ‘const’
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                                                   ^~~~~
../include/yacurscurses.h:140:66: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int mvwaddstr_c(WINDOW* win, int y, int x, const char* str) {
                                                                  ^
In file included from ../include/colors.h:29,
                 from ../include/curstr.h:28,
                 from curstr.cc:22:
../include/yacurscurses.h:163:25: warning: inline variables are only available with -std=c++17 or -std=gnu++17
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                         ^~~~~~
../include/yacurscurses.h:163:25: error: ‘WINDOW’ was not declared in this scope
../include/yacurscurses.h:163:33: error: ‘win’ was not declared in this scope
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                 ^~~
../include/yacurscurses.h:163:38: error: expected primary-expression before ‘int’
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                      ^~~
../include/yacurscurses.h:163:45: error: expected primary-expression before ‘int’
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                             ^~~
../include/yacurscurses.h:163:52: error: expected primary-expression before ‘const’
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                                    ^~~~~
../include/yacurscurses.h:163:69: error: expected primary-expression before ‘int’
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                                                     ^~~
../include/yacurscurses.h:163:74: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int mvwaddnstr_c(WINDOW* win, int y, int x, const char* str, int n) {
                                                                          ^
In file included from ../include/colors.h:29,
                 from ../include/curstr.h:28,
                 from curstr.cc:22:
../include/yacurscurses.h:186:23: warning: inline variables are only available with -std=c++17 or -std=gnu++17
 inline int waddnstr_c(WINDOW* win, const char* str, int n) {
                       ^~~~~~
../include/yacurscurses.h:186:23: error: ‘WINDOW’ was not declared in this scope
../include/yacurscurses.h:186:31: error: ‘win’ was not declared in this scope
 inline int waddnstr_c(WINDOW* win, const char* str, int n) {
                               ^~~
../include/yacurscurses.h:186:36: error: expected primary-expression before ‘const’
 inline int waddnstr_c(WINDOW* win, const char* str, int n) {
                                    ^~~~~
../include/yacurscurses.h:186:53: error: expected primary-expression before ‘int’
 inline int waddnstr_c(WINDOW* win, const char* str, int n) {
                                                     ^~~
../include/yacurscurses.h:186:58: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int waddnstr_c(WINDOW* win, const char* str, int n) {
                                                          ^
make[4]: *** [Makefile:658: libyacurs_la-curstr.lo] Error 1
make[4]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs/src'
make[3]: *** [Makefile:437: all-recursive] Error 1
make[3]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs'
make[2]: *** [Makefile:369: all] Error 2
make[2]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3/libyacurs'
make[1]: *** [Makefile:537: all-recursive] Error 1
make[1]: Leaving directory '/home/skyf/Downloads/yapet/yapet-2.3'
make: *** [Makefile:427: all] Error 2

Thank you for help!

lovelytux

**Comment by RafaelOstertag** [comment]
Hey!

In the same directory where you run `./configure` you should find a file named `config.log`. Can you upload that file to this issue? It'll help to diagnose the problem.

Cheers

**Comment by lovelytux** [comment]
Hey,
thanks for reply.
Here it is:
[config.log](https://github.com/RafaelOstertag/yapet/files/3713998/config.log)

**Comment by RafaelOstertag** [comment]
Thx! Can you also upload the `config.log` that is in in the `libyacurs/` directory?

**Comment by lovelytux** [comment]
Hey,
yes please:
[/libyacurs/config.log](https://github.com/RafaelOstertag/yapet/files/3720622/config.log)

**Comment by RafaelOstertag** [comment]
When looking for the curses header files, the linking stage of the check binary fails and thus the entire check fails. Does `make` still give you errors if you run `configure` like this

    ./configure LDFLAGS='-ltinfow'

and then do a `make`?

**Comment by lovelytux** [comment]
Hey,
that helps! Make runs! Do you need the logs? Thanks!

**Comment by daveloyall** [comment]
Confirmed. I experienced this same problem on Gentoo (fresh install, just updated all packages today).  `LDFLAGS='-ltinfow'` fixed it.

*While I'm here, thank you for `yapet`, I use it ten times a day!*
