### ISSUE TITLE
tests fail with openssl 3

### ISSUE THREAD

**Issue by mwhudson** [RafaelOstertag/yapet#23]
As reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006579 (this is the package as in Debian, but I confirmed current git @ e306fff7df613b0e1c5f1ec1db09df0780fd7db7 fails the same way), tests fail when built against openssl 3. All the failures seem to be of the form "Unable to initialize the digest".

**Comment by RafaelOstertag** [comment]
Thank you for bringing this to my attention. It's fixed in https://github.com/RafaelOstertag/yapet/commit/48cecb226f710c7dd46aff4b0e9a8bb4666a80aa.

Tar balls can be download from the [web page](https://yapet.guengel.ch/downloads.html).

For now, I consider the issue solved.

Cheers
